### ISSUE TITLE
TG-2022-1Levantamentos Iniciais

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol#1]
# Objetivo
* Descrevam aqui:
    * Tema do trabalho (exemplo: App para adoção de PETs"
    * Breve descrição da situação problema (exemplo: Desenvolver um app para facilitar a adoção de Pets, tendo  como objetivo subjacente a criação de uma rede social com pessoas interessadas em cuidar de animais de estimação)
 
# Artefatos
Deverá ser postado **um arquivo**, formato PDF, cujo conteúdo deverá ter:
* Scrum Master 
    * Nome
    *  Responsabilidades
* Product Owner
    * Nome
    * Responsabilidades 
* Development Time
    Nome | papel | Responsabilidade 
    --------| ------ |--------------------
     xxx      |          |                               
     yyy      |          |                              
     zzz      |          |

**Comment by RicardoCruz78** [comment]
Ok ....

**Comment by RicardoCruz78** [comment]
# Objetivo
## Tema
   ###  Sistema Web para Escala de Árbitros de Futebol

## Descrição

 * Existem empresas que prestam serviços aos clubes na modalidade de futebol amador e que tem muita dificuldade de se comunicar com os árbitros para escalar eles para determinadas partidas, o método atual de escala é pelo aplicativo WhatsApp, e em diversos momentos existem desencontros de informações, como endereço, cidade, horário da partida e quem seria os outros integrantes designados.
O objetivo do sistema é facilitar a comunicação e a precisão que as informações serão destinadas.
O sistema irá armazenar dados dos árbitros, cadastrar escalas, confirmar escalas, listar escalas e registrar notas. Os membros da comissão de arbitragem irão escalar os árbitros para determinadas partidas de futebol amador e com as informações irão aprovar se o árbitro tem condições física, psicológica, teóricas e se ele tem experiência suficiente para trabalhar em determinados jogos.)
 
# Artefatos
Segue o artefato descrevendo o Scrum Team
[scrumTeam.pdf](https://github.com/RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol/files/8220024/scrumTeam.pdf)
