### ISSUE TITLE
Sprint#1 - Product Backlog & Sprint Backlog  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol#3]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente**** Product Backlog & Sprint Backlog - no modelo enviado pela **_Profa. Ana Cláudia_** passou para vocês.

**Comment by RicardoCruz78** [comment]
[Product Back Log & Sprint_1603.xlsx](https://github.com/RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol/files/8270635/Product.Back.Log.Sprint_1603.xlsx)

**Comment by RicardoCruz78** [comment]
[Product Back Log & Sprint_1603.xlsx](https://github.com/RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol/files/8270683/Product.Back.Log.Sprint_1603.xlsx)

**Comment by RicardoCruz78** [comment]
[Product Back Log & Sprint_1603.xlsx](https://github.com/RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol/files/8270848/Product.Back.Log.Sprint_1603.xlsx)

**Comment by RicardoCruz78** [comment]
[v2_Product Back Log & Sprint_1603.xlsx](https://github.com/RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol/files/8429975/v2_Product.Back.Log.Sprint_1603.xlsx)
