### ISSUE TITLE
Sprint#1 - Vídeo (gravação do Login + CRUD)  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [RicardoCruz78/YAD188-G07-Escala-de-Abitros-de-Futebol#4]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente****  o vídeo produzido, e que será apresentado em aula

**Comment by RicardoCruz78** [comment]
https://user-images.githubusercontent.com/61611426/158512395-0b9136df-dc74-41e2-a110-ded467b60314.mp4

**Comment by RicardoCruz78** [comment]
https://user-images.githubusercontent.com/61611426/162053597-a93bc3c5-6d52-4498-b624-1ac4d7826846.mp4

Também esta postado no Youtube mediante esse link.                                   https://www.youtube.com/watch?v=ZpIxI02rN5Q
